// Real cron data extracted from OpenClaw
export interface CronJob {
  id: string;
  name: string;
  agent: string;
  schedule: string;
  lastStatus: 'success' | 'warning' | 'error';
  lastRun: string;
  consecutiveErrors: number;
  errorMessage?: string;
  duration: string;
  nextRun: string;
}

export const realCronJobs: CronJob[] = [
  {
    id: "1",
    name: "russ-deal-notifier",
    agent: "Ari",
    schedule: "every 30m",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "59 mins ago",
    consecutiveErrors: 13,
    errorMessage: "model not allowed: anthropic/claude-sonnet-4-6",
    duration: "0.0s",
    nextRun: "In 0 mins",
  },
  {
    id: "2",
    name: "Channel Analysis Queue",
    agent: "Ari",
    schedule: "every 20m",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "11 mins ago",
    consecutiveErrors: 0,
    duration: "95.1s",
    nextRun: "In 8 mins",
  },
  {
    id: "3",
    name: "inbound-email-monitor",
    agent: "Ari",
    schedule: "*/5 * * * *",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "42 mins ago",
    consecutiveErrors: 15,
    errorMessage: "model not allowed: anthropic/claude-sonnet-4-6",
    duration: "0.0s",
    nextRun: "In 17 mins",
  },
  {
    id: "4",
    name: "new-creator-monitor",
    agent: "Ari",
    schedule: "every 30m",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "21 mins ago",
    consecutiveErrors: 11,
    errorMessage: "model not allowed: anthropic/claude-sonnet-4-6",
    duration: "0.0s",
    nextRun: "In 38 mins",
  },
  {
    id: "5",
    name: "local-model-dispatcher",
    agent: "Ari",
    schedule: "every 30m",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "16 mins ago",
    consecutiveErrors: 13,
    errorMessage: "model not allowed: anthropic/claude-sonnet-4-6",
    duration: "0.0s",
    nextRun: "In 43 mins",
  },
  {
    id: "6",
    name: "creator-enrichment-1am",
    agent: "Ari",
    schedule: "0 1 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "23 hours ago",
    consecutiveErrors: 0,
    duration: "556.1s",
    nextRun: "In 52 mins",
  },
  {
    id: "7",
    name: "brand-db-enrich-1",
    agent: "Ari",
    schedule: "0 1 * * *",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "22 hours ago",
    consecutiveErrors: 1,
    errorMessage: "Error: cron: job execution timed out",
    duration: "900.0s",
    nextRun: "In 52 mins",
  },
  {
    id: "8",
    name: "contract-matcher",
    agent: "Ari",
    schedule: "0 * * * *",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "6 mins ago",
    consecutiveErrors: 10,
    errorMessage: "model not allowed: anthropic/claude-sonnet-4-6",
    duration: "0.0s",
    nextRun: "In 53 mins",
  },
  {
    id: "9",
    name: "agentio-pipeline-watchdog",
    agent: "Ari",
    schedule: "*/30 * * * *",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "4 mins ago",
    consecutiveErrors: 14,
    errorMessage: "model not allowed: anthropic/claude-sonnet-4-6",
    duration: "0.0s",
    nextRun: "In 55 mins",
  },
  {
    id: "10",
    name: "brand-reports-enrich-1",
    agent: "Ari",
    schedule: "30 1 * * *",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "22 hours ago",
    consecutiveErrors: 1,
    errorMessage: "Error: cron: job execution timed out",
    duration: "900.0s",
    nextRun: "In 1 hours",
  },
  {
    id: "11",
    name: "creator-enrichment-2am",
    agent: "Ari",
    schedule: "0 2 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "22 hours ago",
    consecutiveErrors: 0,
    duration: "343.9s",
    nextRun: "In 1 hours",
  },
  {
    id: "12",
    name: "brand-db-enrich-2",
    agent: "Ari",
    schedule: "0 2 * * *",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "22 hours ago",
    consecutiveErrors: 4,
    errorMessage: "Error: cron: job execution timed out",
    duration: "900.0s",
    nextRun: "In 1 hours",
  },
  {
    id: "13",
    name: "Educational Discovery",
    agent: "Ari",
    schedule: "0 2 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "21 hours ago",
    consecutiveErrors: 0,
    duration: "72.9s",
    nextRun: "In 1 hours",
  },
  {
    id: "14",
    name: "creator-airtable-sync",
    agent: "Ari",
    schedule: "0 */2 * * *",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "5 mins ago",
    consecutiveErrors: 7,
    errorMessage: "model not allowed: anthropic/claude-sonnet-4-6",
    duration: "0.0s",
    nextRun: "In 1 hours",
  },
  {
    id: "15",
    name: "brand-reports-enrich-2",
    agent: "Ari",
    schedule: "30 2 * * *",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "21 hours ago",
    consecutiveErrors: 3,
    errorMessage: "Error: cron: job execution timed out",
    duration: "900.1s",
    nextRun: "In 2 hours",
  },
  {
    id: "16",
    name: "creator-enrichment-3am",
    agent: "Ari",
    schedule: "0 3 * * *",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "21 hours ago",
    consecutiveErrors: 1,
    errorMessage: "Error: cron: job execution timed out",
    duration: "600.0s",
    nextRun: "In 2 hours",
  },
  {
    id: "17",
    name: "brand-db-enrich-3",
    agent: "Ari",
    schedule: "0 3 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "20 hours ago",
    consecutiveErrors: 0,
    duration: "514.8s",
    nextRun: "In 2 hours",
  },
  {
    id: "18",
    name: "daily-channel-discovery",
    agent: "Ari",
    schedule: "0 3 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "20 hours ago",
    consecutiveErrors: 0,
    duration: "669.3s",
    nextRun: "In 2 hours",
  },
  {
    id: "19",
    name: "daily-backup",
    agent: "Ari",
    schedule: "0 3 * * *",
    lastStatus: "warning" as "success" | "warning" | "error",
    lastRun: "never",
    consecutiveErrors: 0,
    duration: "0.0s",
    nextRun: "In 2 hours",
  },
  {
    id: "20",
    name: "brand-reports-enrich-3",
    agent: "Ari",
    schedule: "30 3 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "44 hours ago",
    consecutiveErrors: 0,
    duration: "594.2s",
    nextRun: "In 3 hours",
  },
  {
    id: "21",
    name: "daily_brand_v1_targets",
    agent: "Ari",
    schedule: "0 4 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "20 hours ago",
    consecutiveErrors: 0,
    duration: "70.3s",
    nextRun: "In 3 hours",
  },
  {
    id: "22",
    name: "creator-enrichment-4am",
    agent: "Ari",
    schedule: "0 4 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "20 hours ago",
    consecutiveErrors: 0,
    duration: "440.7s",
    nextRun: "In 3 hours",
  },
  {
    id: "23",
    name: "brand-reports-enrich-4",
    agent: "Ari",
    schedule: "30 4 * * *",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "19 hours ago",
    consecutiveErrors: 1,
    errorMessage: "Error: cron: job execution timed out",
    duration: "900.0s",
    nextRun: "In 4 hours",
  },
  {
    id: "24",
    name: "6am Ops & Strategy Audit",
    agent: "Ari",
    schedule: "0 5 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "19 hours ago",
    consecutiveErrors: 0,
    duration: "81.4s",
    nextRun: "In 4 hours",
  },
  {
    id: "25",
    name: "overnight-competitive-intel",
    agent: "Ari",
    schedule: "0 5 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "19 hours ago",
    consecutiveErrors: 0,
    duration: "281.0s",
    nextRun: "In 4 hours",
  },
  {
    id: "26",
    name: "daily-meeting-briefs",
    agent: "Arlo",
    schedule: "0 6 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "1 hours ago",
    consecutiveErrors: 0,
    duration: "9.8s",
    nextRun: "In 5 hours",
  },
  {
    id: "27",
    name: "axel-security-check",
    agent: "Axel",
    schedule: "0 6 * * *",
    lastStatus: "warning" as "success" | "warning" | "error",
    lastRun: "never",
    consecutiveErrors: 0,
    duration: "0.0s",
    nextRun: "In 5 hours",
  },
  {
    id: "28",
    name: "security-watchdog",
    agent: "Ari",
    schedule: "0 */6 * * *",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "6 mins ago",
    consecutiveErrors: 3,
    errorMessage: "model not allowed: anthropic/claude-sonnet-4-6",
    duration: "0.0s",
    nextRun: "In 5 hours",
  },
  {
    id: "29",
    name: "Daily 7am Morning Brief for Apple",
    agent: "Ari",
    schedule: "0 7 * * *",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "17 hours ago",
    consecutiveErrors: 1,
    errorMessage: "cron announce delivery failed",
    duration: "91.7s",
    nextRun: "In 6 hours",
  },
  {
    id: "30",
    name: "apple-email-scan",
    agent: "Ari",
    schedule: "*/15 7-21 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "2 hours ago",
    consecutiveErrors: 0,
    duration: "21.7s",
    nextRun: "In 6 hours",
  },
  {
    id: "31",
    name: "fathom-proposal-pipeline",
    agent: "Ari",
    schedule: "*/15 7-21 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "2 hours ago",
    consecutiveErrors: 0,
    duration: "8.6s",
    nextRun: "In 6 hours",
  },
  {
    id: "32",
    name: "creator-topic-enrichment",
    agent: "Ari",
    schedule: "0 7 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "17 hours ago",
    consecutiveErrors: 0,
    duration: "120.1s",
    nextRun: "In 6 hours",
  },
  {
    id: "33",
    name: "bizee-hub-daily-update",
    agent: "Ari",
    schedule: "0 7 * * *",
    lastStatus: "warning" as "success" | "warning" | "error",
    lastRun: "never",
    consecutiveErrors: 0,
    duration: "0.0s",
    nextRun: "In 6 hours",
  },
  {
    id: "34",
    name: "Enhanced Morning Brief with Ops Health",
    agent: "Ari",
    schedule: "30 7 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "16 hours ago",
    consecutiveErrors: 0,
    duration: "11.5s",
    nextRun: "In 7 hours",
  },
  {
    id: "35",
    name: "Daily Agent Dashboard",
    agent: "Ari",
    schedule: "0 8 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "16 hours ago",
    consecutiveErrors: 0,
    duration: "120.2s",
    nextRun: "In 7 hours",
  },
  {
    id: "36",
    name: "memory-filing",
    agent: "Ari",
    schedule: "0 8-22 * * *",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "2 hours ago",
    consecutiveErrors: 2,
    errorMessage: "Error: cron: job execution timed out",
    duration: "60.0s",
    nextRun: "In 7 hours",
  },
  {
    id: "37",
    name: "axel-build-health",
    agent: "Axel",
    schedule: "0 8,10,12,14,16,18,20,22 * * *",
    lastStatus: "warning" as "success" | "warning" | "error",
    lastRun: "never",
    consecutiveErrors: 0,
    duration: "0.0s",
    nextRun: "In 7 hours",
  },
  {
    id: "38",
    name: "axel-github-watch",
    agent: "Axel",
    schedule: "0 8,12,16,20 * * *",
    lastStatus: "warning" as "success" | "warning" | "error",
    lastRun: "never",
    consecutiveErrors: 0,
    duration: "0.0s",
    nextRun: "In 7 hours",
  },
  {
    id: "39",
    name: "80K Discovery Checkpoint",
    agent: "Ari",
    schedule: "0 */8 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "7 mins ago",
    consecutiveErrors: 0,
    duration: "3.6s",
    nextRun: "In 7 hours",
  },
  {
    id: "40",
    name: "arlo-memory-filing",
    agent: "Arlo",
    schedule: "30 8-22 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "1 hours ago",
    consecutiveErrors: 0,
    duration: "9.6s",
    nextRun: "In 8 hours",
  },
  {
    id: "41",
    name: "axel-memory-filing",
    agent: "Axel",
    schedule: "30 8-22 * * *",
    lastStatus: "warning" as "success" | "warning" | "error",
    lastRun: "never",
    consecutiveErrors: 0,
    duration: "0.0s",
    nextRun: "In 8 hours",
  },
  {
    id: "42",
    name: "email-check-9am",
    agent: "Ari",
    schedule: "0 9 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "15 hours ago",
    consecutiveErrors: 0,
    duration: "60.3s",
    nextRun: "In 8 hours",
  },
  {
    id: "43",
    name: "followup-engine",
    agent: "Arlo",
    schedule: "0 9 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "1 hours ago",
    consecutiveErrors: 0,
    duration: "43.3s",
    nextRun: "In 8 hours",
  },
  {
    id: "44",
    name: "axel-morning-standup",
    agent: "Axel",
    schedule: "0 9 * * 1-5",
    lastStatus: "warning" as "success" | "warning" | "error",
    lastRun: "never",
    consecutiveErrors: 0,
    duration: "0.0s",
    nextRun: "In 8 hours",
  },
  {
    id: "45",
    name: "arlo-heartbeat",
    agent: "Arlo",
    schedule: "0 9,12,15,18 * * 1-5",
    lastStatus: "warning" as "success" | "warning" | "error",
    lastRun: "never",
    consecutiveErrors: 0,
    duration: "0.0s",
    nextRun: "In 8 hours",
  },
  {
    id: "46",
    name: "aaron-daily-briefing",
    agent: "Ari",
    schedule: "0 10 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "14 hours ago",
    consecutiveErrors: 0,
    duration: "45.5s",
    nextRun: "In 9 hours",
  },
  {
    id: "47",
    name: "aaron-typo-roast",
    agent: "Ari",
    schedule: "0 12 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "12 hours ago",
    consecutiveErrors: 0,
    duration: "30.2s",
    nextRun: "In 11 hours",
  },
  {
    id: "48",
    name: "email-check-1pm",
    agent: "Ari",
    schedule: "0 13 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "11 hours ago",
    consecutiveErrors: 0,
    duration: "45.6s",
    nextRun: "In 12 hours",
  },
  {
    id: "49",
    name: "email-check-6pm",
    agent: "Ari",
    schedule: "0 18 * * *",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "6 hours ago",
    consecutiveErrors: 0,
    duration: "71.4s",
    nextRun: "In 17 hours",
  },
  {
    id: "50",
    name: "daily-learning-summary",
    agent: "Ari",
    schedule: "0 19 * * *",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "5 hours ago",
    consecutiveErrors: 1,
    errorMessage: "model not allowed: anthropic/claude-sonnet-4-6",
    duration: "0.0s",
    nextRun: "In 18 hours",
  },
  {
    id: "51",
    name: "arlo-daily-digest",
    agent: "Arlo",
    schedule: "0 21 * * *",
    lastStatus: "warning" as "success" | "warning" | "error",
    lastRun: "never",
    consecutiveErrors: 0,
    duration: "0.0s",
    nextRun: "In 20 hours",
  },
  {
    id: "52",
    name: "nightly-tier-classification",
    agent: "Ari",
    schedule: "0 0 * * *",
    lastStatus: "error" as "success" | "warning" | "error",
    lastRun: "7 mins ago",
    consecutiveErrors: 1,
    errorMessage: "model not allowed: anthropic/claude-sonnet-4-6",
    duration: "0.0s",
    nextRun: "In 23 hours",
  },
  {
    id: "53",
    name: "api-cost-monitor",
    agent: "Ari",
    schedule: "every 72h",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "34 hours ago",
    consecutiveErrors: 0,
    duration: "232.2s",
    nextRun: "In 37 hours",
  },
  {
    id: "54",
    name: "weekly-read-later-digest",
    agent: "Ari",
    schedule: "0 15 * * FRI",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "129 hours ago",
    consecutiveErrors: 0,
    duration: "6.7s",
    nextRun: "In 38 hours",
  },
  {
    id: "55",
    name: "followup-weekly-summary",
    agent: "Arlo",
    schedule: "0 16 * * 5",
    lastStatus: "warning" as "success" | "warning" | "error",
    lastRun: "never",
    consecutiveErrors: 0,
    duration: "0.0s",
    nextRun: "In 39 hours",
  },
  {
    id: "56",
    name: "Weekly Feature Requests Digest",
    agent: "Ari",
    schedule: "0 18 * * FRI",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "126 hours ago",
    consecutiveErrors: 0,
    duration: "17.3s",
    nextRun: "In 41 hours",
  },
  {
    id: "57",
    name: "weekly-avg-views-update",
    agent: "Ari",
    schedule: "0 4 * * 6",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "115 hours ago",
    consecutiveErrors: 0,
    duration: "1827.8s",
    nextRun: "In 51 hours",
  },
  {
    id: "58",
    name: "weekly-security-audit",
    agent: "Ari",
    schedule: "0 8 * * 6",
    lastStatus: "warning" as "success" | "warning" | "error",
    lastRun: "never",
    consecutiveErrors: 0,
    duration: "0.0s",
    nextRun: "In 55 hours",
  },
  {
    id: "59",
    name: "weekly-sponsorship-monitor",
    agent: "Ari",
    schedule: "0 6 * * 0",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "90 hours ago",
    consecutiveErrors: 0,
    duration: "99.2s",
    nextRun: "In 77 hours",
  },
  {
    id: "60",
    name: "context-pruning",
    agent: "Ari",
    schedule: "0 22 * * 0",
    lastStatus: "warning" as "success" | "warning" | "error",
    lastRun: "never",
    consecutiveErrors: 0,
    duration: "0.0s",
    nextRun: "In 93 hours",
  },
  {
    id: "61",
    name: "arlo-context-pruning",
    agent: "Arlo",
    schedule: "0 22 * * 0",
    lastStatus: "warning" as "success" | "warning" | "error",
    lastRun: "never",
    consecutiveErrors: 0,
    duration: "0.0s",
    nextRun: "In 93 hours",
  },
  {
    id: "62",
    name: "axel-context-pruning",
    agent: "Axel",
    schedule: "0 22 * * 0",
    lastStatus: "warning" as "success" | "warning" | "error",
    lastRun: "never",
    consecutiveErrors: 0,
    duration: "0.0s",
    nextRun: "In 93 hours",
  },
  {
    id: "63",
    name: "weekly-creator-drought-monitor",
    agent: "Ari",
    schedule: "0 8 * * 1",
    lastStatus: "warning" as "success" | "warning" | "error",
    lastRun: "never",
    consecutiveErrors: 0,
    duration: "0.0s",
    nextRun: "In 103 hours",
  },
  {
    id: "64",
    name: "cross-sell-weekly",
    agent: "Arlo",
    schedule: "0 8 * * 1",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "1 hours ago",
    consecutiveErrors: 0,
    duration: "72.2s",
    nextRun: "In 103 hours",
  },
  {
    id: "65",
    name: "monthly-email-draft",
    agent: "Ari",
    schedule: "0 9 1-7 * 1",
    lastStatus: "warning" as "success" | "warning" | "error",
    lastRun: "never",
    consecutiveErrors: 0,
    duration: "0.0s",
    nextRun: "In 104 hours",
  },
  {
    id: "66",
    name: "reengagement-check",
    agent: "Ari",
    schedule: "0 10 * * 1",
    lastStatus: "success" as "success" | "warning" | "error",
    lastRun: "62 hours ago",
    consecutiveErrors: 0,
    duration: "45.1s",
    nextRun: "In 105 hours",
  }
];